# Generated by Django 3.2 on 2023-03-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_posts_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.CharField(default='Blog main body', max_length=1000000),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='Blog', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='references',
            field=models.CharField(default='Blog references', max_length=10000),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Blog Title', max_length=100),
        ),
    ]
