# Generated by Django 4.1.7 on 2023-04-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20230316_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='Others', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='references',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
