# Generated by Django 4.1.7 on 2023-05-03 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_remove_post_dislikes_remove_post_hearts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='post',
            name='heart',
        ),
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
    ]
