# Generated by Django 4.1.7 on 2023-05-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_post_dislikes_post_likes_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
